development:
  adapter: postgresql
  encoding: unicode
  database: meet_the_memes_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: meet_the_memes_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: meet_the_memes_production
  pool: 5
  username:
  password:
